defaults: ../../grpo_math_1B.yaml
grpo:
  num_prompts_per_step: 64
  num_generations_per_prompt: 32
  max_num_steps: 30
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-qwen2.5-7b-instruct-4n8g-megatron
  save_period: 100
policy:
  model_name: Qwen/Qwen2.5-7B-Instruct
  train_micro_batch_size: 1
  logprob_batch_size: 2
  max_total_sequence_length: 4096
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
    tensor_model_parallel_size: 2
    scheduler:
      lr_warmup_iters: 50
  make_sequence_length_divisible_by: 4
  optimizer:
    kwargs:
      lr: 3.0e-07
  scheduler:
  - name: torch.optim.lr_scheduler.LinearLR
    kwargs:
      start_factor: 0.1
      end_factor: 1
      total_iters: 13
  - name: torch.optim.lr_scheduler.ConstantLR
    kwargs:
      factor: 1
      total_iters: 10000000000
  - milestones:
    - 13
  generation:
    max_new_tokens: 4096
    vllm_cfg:
      tensor_parallel_size: 4
      max_model_len: 4096
data:
  max_input_seq_length: 4096
logger:
  log_dir: logs/grpo-qwen2.5-7b-instruct-4n8g-megatron
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-qwen2.5-7b-instruct-4n8g-megatron
cluster:
  gpus_per_node: 8
  num_nodes: 4
