defaults: ../../grpo_math_1B.yaml
grpo:
  val_period: -1
loss_fn:
  reference_policy_kl_penalty: 0.04
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo_megatron
  save_period: 10000
policy:
  model_name: moonshotai/Moonlight-16B-A3B-Instruct
  train_micro_batch_size: 1
  generation_batch_size: 64
  logprob_batch_size: 1
  max_total_sequence_length: 8192
  dtensor_cfg:
    enabled: false
  sequence_packing:
    enabled: false
    algorithm: modified_ffd
  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  optimizer: null
  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    expert_model_parallel_size: 4
    pipeline_model_parallel_size: 4
    num_layers_in_first_pipeline_stage: 7
    num_layers_in_last_pipeline_stage: 6
    apply_rope_fusion: false
    optimizer:
      lr: 1.0e-06
    scheduler:
      lr_warmup_iters: 50
logger:
  monitor_gpus: false
  wandb:
    name: grpo-moonlight-16B-A3B-Instruct
cluster:
  gpus_per_node: 8
  num_nodes: 4
