defaults: ../../grpo_math_1B.yaml
grpo:
  num_prompts_per_step: 64
  num_generations_per_prompt: 32
  max_num_steps: 500
checkpointing:
  checkpoint_dir: results/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long
policy:
  model_name: meta-llama/Llama-3.1-8B-Instruct
  tokenizer:
    name: meta-llama/Llama-3.1-8B-Instruct
  train_micro_batch_size: 1
  logprob_batch_size: 2
  max_total_sequence_length: 4096
  dynamic_batching:
    enabled: true
  sequence_packing:
    enabled: false
  make_sequence_length_divisible_by: 1
  optimizer:
    kwargs:
      lr: 3.0e-07
  scheduler:
  - name: torch.optim.lr_scheduler.LinearLR
    kwargs:
      start_factor: 0.1
      end_factor: 1
      total_iters: 13
  - name: torch.optim.lr_scheduler.ConstantLR
    kwargs:
      factor: 1
      total_iters: 10000000000
  - milestones:
    - 13
  generation:
    max_new_tokens: 4096
    vllm_cfg:
      max_model_len: 4096
data:
  max_input_seq_length: 4096
logger:
  log_dir: logs/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long
cluster:
  gpus_per_node: 8
  num_nodes: 4
