# GRPO Algorithm Configuration
defaults: "grpo-deepscaler-1.5b-8K.yaml"

loss_fn:
  reference_policy_kl_penalty: 0.001
  ratio_clip_max: 0.28


policy:
  max_total_sequence_length: 16384

  dtensor_cfg:
    enabled: true
    cpu_offload: true
    sequence_parallel: true
    activation_checkpointing: true
    tensor_parallel_size: 2
    context_parallel_size: 1
    custom_parallel_plan: null

  dynamic_batching:
    enabled: False
